version: '3.7'
services:
    aws-localstack:
        image: localstack/localstack:0.10.8 # latest at the time of development     
        container_name: aws-localstack
        restart: always
        volumes:
        - "./localstack:/tmp/localstack/data"
        - "./lambdaS3:/lambda_deploy"
        networks:
        - ${COMPOSE_PROJECT_NAME}_net
        environment:
        - SERVICES=s3,lambda,cloudformation
        - DATA_DIR=/tmp/localstack/data
        - LAMBDA_EXECUTOR=docker
        - DEFAULT_REGION=us-east-1
        - LAMBDA_REMOTE_DOCKER=false
        - DEBUG=3
        ports:
        - "4567-4599:4567-4599" # all services
        - "8080:8080"
    awslin: 
        build: ./
        init: true
        restart: always
        container_name: awslin
        networks:
        - webappnet
        - ${COMPOSE_PROJECT_NAME}_net
        volumes:
        -   type: bind
            source: ./mvc_ator_webapp
            target: /webapp
        ports:
        - "5000:5000"
        - "5001:5001"
        command: sh -c "cd /webapp&&dotnet build --force&&dotnet run --urls=http://0.0.0.0:5000"
     #   command: sh -c "cd /webapp&&dotnet run --urls=http://0.0.0.0:5000"
networks:
    webappnet:
    localaws_net:        